### PR TITLE
WIP: from lazyeval to rlang

### PR DESCRIPTION
**Pull request by christophsax**
@krlmlr

- all verbs using rlang
- removed dependency on lazyeval
- added corresponding tests from dplyr: non working tests are commented out, should be removed and documented.
- should resolve several issues, e.g.,  #31, #54, #51, #43, #17.
- open / to be discussed: utility function `common_env()` does not always give the env we want. Using some variants in the code. Should be analyzed and unified.

### CODE REVIEW

**Comment by lionel-** [comment]
Thanks for working on this Christoph.

Some stuff from my former attempt might be relevant: https://github.com/hadley/dtplyr/compare/master...lionel-:port-tidyeval?expand=1

In particular in the files `utils.R`, `utils-expr.R` and `predicates.R`. I don't remember much but I think instead of finding a common environment, I was flattening incoming quosures with `quo_expr(warn = TRUE)`.

**Comment by hadley** [comment]
@christophsax it's been a while - are you interested in doing a little more to finish this off? I think it just needs a NEWS entry, and to make sure the tests that you've commented out are replaced with `skip()`s. Then I'll finish it off.

**Comment by christophsax** [comment]
Yes, I can do that. Perhaps @krlmlr can also advise me on the details?

**Comment by hadley** [comment]
Oh I looked more closely at the tests — it seems like you just copied and pasted the tests from dplyr, and you've already replaced the comments with skips.  In that case, all you need to do is add a bullet to NEWS? It should briefly [describe the change](http://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

It would also be useful if you could include `Fixes #123` for the issues that you can confirm this PR resolves.

**Comment by christophsax** [comment]
Made a few adjustments to the tests, so the checks are passing again. I copy pasted and adjusted the tests for select again - something that probably should be done for the other verbs as well. Some tests need additional adjustments, a few are performed on tibbles or data.frames, so having them passing doesn't mean much.

I think some of the `group_by()` operations don't work as they should. 

Will look into both, but it will take me a few days.

**Comment by hadley** [comment]
I think it makes sense to merge this now, and then work through verb-by-verb to reduce the tests to the minimum needed. Thanks for your work on this so far!

**Comment by christophsax** [comment]
Sounds reasonable, and thanks for updating the news. I will do a separate PR for each verb I am working on.

**Pull request merged**
